name: Java with Nexus Repository

on:
  push:
    tags: 
      - '[1-9]+.[0-9]+.[0-9]+\-RELEASE'
#    branches: main

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8.0.292+10'
        distribution: 'adopt'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
#        gpg-passphrase: MAVEN_GPG_PASSPHRASE
#        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/*}" >> $GITHUB_ENV

    - name: Test
      run: |
        echo ${{ github.event.release.tag_name }}
        echo ${{ env.RELEASE_VERSION }}
        echo $MAVEN_GPG_PASSPHRASE
        echo ${{ secrets.MAVEN_GPG_PASSPHRASE }}

    - name: Set projects Maven version to GitHub Action GUI set version
      run: mvn versions:set "-DnewVersion=$RELEASE_VERSION"

#    - name: Publish package
#      run: mvn clean deploy -B -U -P release

      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        
